In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns
from xgboost import XGBRegressor
from xgboost import plot_importance
import matplotlib.pyplot as plt

In [2]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [3]:
data_train = pd.read_csv('/home/vanchhit/Downloads/train (1).csv')
data_train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [4]:
data_train.describe().to_csv(r'describbe.csv')

from IPython.display import FileLink
FileLink(r'describbe.csv')

/home/vanchhit/joyconda/describbe.csv

In [5]:
data_train.shape

(1460, 81)

In [6]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()

In [7]:
data_train["MSZoning"]=l1.fit_transform(data_train["MSZoning"])
data_train["Street"]=l1.fit_transform(data_train["Street"])
data_train["Alley"]=l1.fit_transform(data_train["Alley"])
data_train["LotShape"]=l1.fit_transform(data_train["LotShape"])
data_train["LandContour"]=l1.fit_transform(data_train["LandContour"])
data_train["Utilities"]=l1.fit_transform(data_train["Utilities"])
data_train["LotConfig"]=l1.fit_transform(data_train["LotConfig"])
data_train["Neighborhood"]=l1.fit_transform(data_train["Neighborhood"])
data_train["LandSlope"]=l1.fit_transform(data_train["LandSlope"])
data_train["Condition1"]=l1.fit_transform(data_train["Condition1"])
data_train["Condition2"]=l1.fit_transform(data_train["Condition2"])
data_train["BldgType"]=l1.fit_transform(data_train["BldgType"])
data_train["HouseStyle"]=l1.fit_transform(data_train["HouseStyle"])
data_train["RoofStyle"]=l1.fit_transform(data_train["RoofStyle"])
data_train["RoofMatl"]=l1.fit_transform(data_train["RoofMatl"])
data_train["Exterior1st"]=l1.fit_transform(data_train["Exterior1st"])
data_train["Exterior2nd"]=l1.fit_transform(data_train["Exterior2nd"])
data_train["MasVnrType"]=l1.fit_transform(data_train["MasVnrType"])
data_train["ExterQual"]=l1.fit_transform(data_train["ExterQual"])
data_train["ExterCond"]=l1.fit_transform(data_train["ExterCond"])
data_train["BsmtExposure"]=l1.fit_transform(data_train["BsmtExposure"])
data_train["Foundation"]=l1.fit_transform(data_train["Foundation"])
data_train["BsmtQual"]=l1.fit_transform(data_train["BsmtQual"])
data_train["BsmtCond"]=l1.fit_transform(data_train["BsmtCond"])
data_train["BsmtFinType1"]=l1.fit_transform(data_train["BsmtFinType1"])
data_train["BsmtFinType2"]=l1.fit_transform(data_train["BsmtFinType2"])
data_train["Heating"]=l1.fit_transform(data_train["Heating"])
data_train["HeatingQC"]=l1.fit_transform(data_train["HeatingQC"])
data_train["CentralAir"]=l1.fit_transform(data_train["CentralAir"])
data_train["Electrical"]=l1.fit_transform(data_train["Electrical"])
data_train["KitchenQual"]=l1.fit_transform(data_train["KitchenQual"])
data_train["Functional"]=l1.fit_transform(data_train["Functional"])
data_train["FireplaceQu"]=l1.fit_transform(data_train["FireplaceQu"])
data_train["GarageType"]=l1.fit_transform(data_train["GarageType"])
data_train["GarageYrBlt"]=l1.fit_transform(data_train["GarageYrBlt"])
data_train["GarageFinish"]=l1.fit_transform(data_train["GarageFinish"])
data_train["GarageQual"]=l1.fit_transform(data_train["GarageQual"])
data_train["GarageCond"]=l1.fit_transform(data_train["GarageCond"])
data_train["PavedDrive"]=l1.fit_transform(data_train["PavedDrive"])
data_train["PoolQC"]=l1.fit_transform(data_train["PoolQC"])
data_train["Fence"]=l1.fit_transform(data_train["Fence"])
data_train["MiscFeature"]=l1.fit_transform(data_train["MiscFeature"])
data_train["SaleType"]=l1.fit_transform(data_train["SaleType"])
data_train["SaleCondition"]=l1.fit_transform(data_train["SaleCondition"])

In [8]:
data_train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,1,2,3,3,0,...,0,3,4,4,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,2,3,3,0,...,0,3,4,4,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,2,0,3,0,...,0,3,4,4,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,2,0,3,0,...,0,3,4,4,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,2,0,3,0,...,0,3,4,4,0,12,2008,8,4,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,3,62.0,7917,1,2,3,3,0,...,0,3,4,4,0,8,2007,8,4,175000
1456,1457,20,3,85.0,13175,1,2,3,3,0,...,0,3,2,4,0,2,2010,8,4,210000
1457,1458,70,3,66.0,9042,1,2,3,3,0,...,0,3,0,2,2500,5,2010,8,4,266500
1458,1459,20,3,68.0,9717,1,2,3,3,0,...,0,3,4,4,0,4,2010,8,4,142125
1459,1460,20,3,75.0,9937,1,2,3,3,0,...,0,3,4,4,0,6,2008,8,4,147500

In [9]:
data_train.replace([np.inf,-np.inf], np.nan, inplace=True)

In [10]:
data_train.fillna(999, inplace=True)

In [11]:
x=data_train.iloc[:,1:-1].values
y=data_train.iloc[:,-1].values

In [12]:
x.shape

(1460, 79)

In [13]:
y

array([208500, 181500, 223500, ..., 266500, 142125, 147500])

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=11)

In [15]:
data_train.isnull().sum().tail(40)

CentralAir       0
Electrical       0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
KitchenQual      0
TotRmsAbvGrd     0
Functional       0
Fireplaces       0
FireplaceQu      0
GarageType       0
GarageYrBlt      0
GarageFinish     0
GarageCars       0
GarageArea       0
GarageQual       0
GarageCond       0
PavedDrive       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
PoolQC           0
Fence            0
MiscFeature      0
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
dtype: int64

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [17]:
xgb=XGBRegressor(n_estimators = 200,max_depth = 2)
xgb.fit(x_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=2, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=200, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, ...)

In [18]:
xgb.score(x_train, y_train)

0.9792372066089814

In [19]:
xgb.score(x_test, y_test)

0.8917772554883954

In [20]:
data_test = pd.read_csv('/home/vanchhit/Downloads/test.csv')
data_test

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [21]:
data_test.shape, x_train.shape

((1459, 80), (1168, 79))

In [22]:
data_test["Street"]=l1.fit_transform(data_test["Street"])

In [23]:
data_test

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,1,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,1,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,1,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,1,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,1,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,1,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,1,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,1,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,1,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,1,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [24]:
for col in data_test.columns:
    if data_test[col].dtype == object:
        data_test[col] = data_test[col].astype(str)
        data_test[col]=l1.fit_transform(data_test[col])
print(data_test)

        Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
0     1461          20         2         80.0    11622       1      2
1     1462          20         3         81.0    14267       1      2
2     1463          60         3         74.0    13830       1      2
3     1464          60         3         78.0     9978       1      2
4     1465         120         3         43.0     5005       1      2
...    ...         ...       ...          ...      ...     ...    ...
1454  2915         160         4         21.0     1936       1      2
1455  2916         160         4         21.0     1894       1      2
1456  2917          20         3        160.0    20000       1      2
1457  2918          85         3         62.0    10441       1      2
1458  2919          60         3         74.0     9627       1      2

      LotShape  LandContour  Utilities  ...  ScreenPorch  PoolArea  PoolQC  \
0            3            3          0  ...          120         0       2
1            0            3          0  ...            0         0       2
2            0            3          0  ...            0         0       2
3            0            3          0  ...            0         0       2
4            0            1          0  ...          144         0       2
...        ...          ...        ...  ...          ...       ...     ...
1454         3            3          0  ...            0         0       2
1455         3            3          0  ...            0         0       2
1456         3            3          0  ...            0         0       2
1457         3            3          0  ...            0         0       2
1458         3            3          0  ...            0         0       2

      Fence  MiscFeature  MiscVal  MoSold  YrSold  SaleType  SaleCondition
0         2            3        0       6    2010         8              4
1         4            0    12500       6    2010         8              4
2         2            3        0       3    2010         8              4
3         4            3        0       6    2010         8              4
4         4            3        0       1    2010         8              4
...     ...          ...      ...     ...     ...       ...            ...
1454      4            3        0       6    2006         8              4
1455      4            3        0       4    2006         8              0
1456      4            3        0       9    2006         8              0
1457      2            2      700       7    2006         8              4
1458      4            3        0      11    2006         8              4

[1459 rows x 80 columns]

In [25]:
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1459 non-null   int64
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   int64
 6   Alley          1459 non-null   int64
 7   LotShape       1459 non-null   int64
 8   LandContour    1459 non-null   int64
 9   Utilities      1459 non-null   int64
 10  LotConfig      1459 non-null   int64
 11  LandSlope      1459 non-null   int64
 12  Neighborhood   1459 non-null   int64
 13  Condition1     1459 non-null   int64
 14  Condition2     1459 non-null   int64
 15  BldgType       1459 non-null   int64
 16  HouseStyle     1459 non-null   int64
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   int64
 22  RoofMatl       1459 non-null   int64
 23  Exterior1st    1459 non-null   int64
 24  Exterior2nd    1459 non-null   int64
 25  MasVnrType     1459 non-null   int64
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   int64
 28  ExterCond      1459 non-null   int64
 29  Foundation     1459 non-null   int64
 30  BsmtQual       1459 non-null   int64
 31  BsmtCond       1459 non-null   int64
 32  BsmtExposure   1459 non-null   int64
 33  BsmtFinType1   1459 non-null   int64
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1459 non-null   int64
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   int64
 40  HeatingQC      1459 non-null   int64
 41  CentralAir     1459 non-null   int64
 42  Electrical     1459 non-null   int64
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1459 non-null   int64
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1459 non-null   int64
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    1459 non-null   int64
 58  GarageType     1459 non-null   int64
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1459 non-null   int64
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1459 non-null   int64
 64  GarageCond     1459 non-null   int64
 65  PavedDrive     1459 non-null   int64
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         1459 non-null   int64
 73  Fence          1459 non-null   int64
 74  MiscFeature    1459 non-null   int64
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1459 non-null   int64
 79  SaleCondition  1459 non-null   int64
dtypes: float64(11), int64(69)
memory usage: 912.0 KB

In [26]:
data_test.fillna(999, inplace=True)

In [27]:
SalePrice=xgb.predict(sc.transform(data_test.iloc[:,1:].values))
SalePrice.shape

(1459,)

In [28]:
data_test.insert(1,"SalePrice",SalePrice)
data_test

,Id,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,125538.406250,20,2,80.0,11622,1,2,3,3,...,120,0,2,2,3,0,6,2010,8,4
1,1462,160531.812500,20,3,81.0,14267,1,2,0,3,...,0,0,2,4,0,12500,6,2010,8,4
2,1463,184681.656250,60,3,74.0,13830,1,2,0,3,...,0,0,2,2,3,0,3,2010,8,4
3,1464,178930.515625,60,3,78.0,9978,1,2,0,3,...,0,0,2,4,3,0,6,2010,8,4
4,1465,183522.953125,120,3,43.0,5005,1,2,0,1,...,144,0,2,4,3,0,1,2010,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,81831.039062,160,4,21.0,1936,1,2,3,3,...,0,0,2,4,3,0,6,2006,8,4
1455,2916,71683.210938,160,4,21.0,1894,1,2,3,3,...,0,0,2,4,3,0,4,2006,8,0
1456,2917,153756.984375,20,3,160.0,20000,1,2,3,3,...,0,0,2,4,3,0,9,2006,8,0
1457,2918,117644.250000,85,3,62.0,10441,1,2,3,3,...,0,0,2,2,2,700,7,2006,8,4
1458,2919,206455.500000,60,3,74.0,9627,1,2,3,3,...,0,0,2,4,3,0,11,2006,8,4

In [29]:
data_test

,Id,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,125538.406250,20,2,80.0,11622,1,2,3,3,...,120,0,2,2,3,0,6,2010,8,4
1,1462,160531.812500,20,3,81.0,14267,1,2,0,3,...,0,0,2,4,0,12500,6,2010,8,4
2,1463,184681.656250,60,3,74.0,13830,1,2,0,3,...,0,0,2,2,3,0,3,2010,8,4
3,1464,178930.515625,60,3,78.0,9978,1,2,0,3,...,0,0,2,4,3,0,6,2010,8,4
4,1465,183522.953125,120,3,43.0,5005,1,2,0,1,...,144,0,2,4,3,0,1,2010,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,81831.039062,160,4,21.0,1936,1,2,3,3,...,0,0,2,4,3,0,6,2006,8,4
1455,2916,71683.210938,160,4,21.0,1894,1,2,3,3,...,0,0,2,4,3,0,4,2006,8,0
1456,2917,153756.984375,20,3,160.0,20000,1,2,3,3,...,0,0,2,4,3,0,9,2006,8,0
1457,2918,117644.250000,85,3,62.0,10441,1,2,3,3,...,0,0,2,2,2,700,7,2006,8,4
1458,2919,206455.500000,60,3,74.0,9627,1,2,3,3,...,0,0,2,4,3,0,11,2006,8,4

In [30]:
sample=data_test.iloc[:,[0,1]]
sample

import os
sample.to_csv(r'sample_submission.csv',index=False)


from IPython.display import FileLink
FileLink(r'sample_submission.csv')

/home/vanchhit/joyconda/sample_submission.csv

In [31]:
sample

        Id      SalePrice
0     1461  125538.406250
1     1462  160531.812500
2     1463  184681.656250
3     1464  178930.515625
4     1465  183522.953125
...    ...            ...
1454  2915   81831.039062
1455  2916   71683.210938
1456  2917  153756.984375
1457  2918  117644.250000
1458  2919  206455.500000

[1459 rows x 2 columns]